amcl:
  ros__parameters:
    use_sim_time: true
    scan_topic: /mower_robot/scan
    map_topic: /map
    base_frame_id: base_link
    odom_frame_id: odom
    global_frame_id: map
    transform_tolerance: 0.2
    max_particles: 2000
    min_particles: 500

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      resolution: 0.05
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: /mower_robot/scan
          max_obstacle_height: 2.0
          clearing: true
          marking: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.55

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: /mower_robot/scan
          max_obstacle_height: 2.0
          clearing: true
          marking: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.55

planner_server:
  ros__parameters:
    use_sim_time: true
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_teb_planner/TebLocalPlannerROS"
      max_vel_x: 0.4
      max_vel_theta: 0.8
      acc_lim_x: 0.5
      acc_lim_theta: 0.5
      min_obstacle_dist: 0.3
      odom_topic: /mower_robot/odom

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_teb_planner/TebLocalPlannerROS"
      max_vel_x: 0.4
      max_vel_theta: 0.8
      acc_lim_x: 0.5
      acc_lim_theta: 0.5
      min_obstacle_dist: 0.3
      odom_topic: /mower_robot/odom
