controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_teb_controller::TebLocalPlannerROS"
      robot_base_frame: base_link
      transform_tolerance: 0.3
      max_global_plan_lookahead_dist: 3.0
      max_robot_pose_search_dist: 10.0
      obstacle_proximity_ratio: 0.5
      min_obstacle_dist: 0.3
      max_vel_x: 0.5
      max_vel_theta: 1.0
      acc_lim_x: 1.0
      acc_lim_theta: 2.0
      footprint_model:
        type: "polygon"
        vertices: [[0.2, 0.15], [0.2, -0.15], [-0.2, -0.15], [-0.2, 0.15]]  # Matches 0.4x0.3m box

planner_server:
  ros__parameters:
    use_sim_time: true
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_final_approach_orientation: false

bt_navigator:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /mower_robot/odom
    default_nav_to_pose_bt_xml: /opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml

amcl:
  ros__parameters:
    use_sim_time: true
    min_particles: 500
    max_particles: 5000
    pf_err: 0.05
    pf_z: 0.99
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    transform_tolerance: 0.3
    scan_topic: /mower_robot/scan