slam_toolbox:
  ros__parameters:
    mode: mapping
    use_sim_time: true
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5
    scan_topic: /mower_robot/scan
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    transform_publish_period: 0.02
    map_update_interval: 5.0
    resolution: 0.05
    max_laser_range: 10.0
